name: Pull Requests / Weekly QA

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # ratchet:actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -o awesome-docker ./cmd/awesome-docker

      - name: Validate
        run: ./awesome-docker validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
